### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by prodnet** [gsurma/password_cracker#1]
Where can be found this code ?

**Comment by gregsurma** [comment]
It's there: [https://github.com/gsurma/text_predictor](https://github.com/gsurma/text_predictor)


You just need to provide a dataset inside` ./data` folder. Similarly to:  [https://github.com/gsurma/text_predictor#datasets](https://github.com/gsurma/text_predictor#datasets)

**Comment by gsurma** [comment]
It's there: https://github.com/gsurma/text_predictor

You just need to provide a dataset inside ./data folder. Similarly to: https://github.com/gsurma/text_predictor#datasets

**Comment by prodnet** [comment]
Please give a concrete example of use.
Thanks.
